name: Build and Upload DLL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./HelloLib/HelloLib.csproj

      - name: Build (Release)
        run: dotnet build ./HelloLib/HelloLib.csproj --configuration Release --no-restore

      - name: Publish DLL
        run: dotnet publish ./HelloLib/HelloLib.csproj --configuration Release --no-build --output ./output

      - name: List output files
        run: ls -R ./output

      - name: Upload artifact (DLL)
        uses: actions/upload-artifact@v4
        with:
          name: HelloLib-DLL
          path: ./output/**/*.dll
